config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :splash, only: [:index]
  resources :groups do
    resources :expenses
  end

  resources :not_found, only: [:index]

  # Defines the root path route ("/")
  root 'splash#index'
  get '/unauthorized', to: 'unauthorized#index'
  
  match '*unmatched', to: 'application#not_found_method', via: :all, constraints: ->(req) do
    req.path.exclude? 'rails/active_storage'
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :group_expenses
  has_many :expenses, through: :group_expenses
  has_one_attached :icon

  validates :name, presence: true, length: { in: 2..300 }
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource

  before_action :find_user
  before_action :find_group, only: %i[show edit update destroy]

  def index
    @groups = @user.groups.all
  end

  def show; end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = @user
    if @group.save
      redirect_to groups_path, notice: 'Group created successfully'
    else
      flash.now[:alert] = @group.errors.full_messages.first if @group.errors.any?
      render :new, status: 400
    end
  end

  def edit; end

  def update
    if @group.update(group_params)
      redirect_to group_path(id: @group.id), notice: 'Group updated successfully'
    else
      flash.now[:alert] = @group.errors.full_messages.first if @group.errors.any?
      render :edit, status: 400
    end
  end

  # rubocop:disable Lint/UselessAssignment
  def destroy
    if can? :edit, @group
      @group_expenses = GroupExpense.where(group_id: @group.id)
      @group_expenses.each do |group_expense|
        expense_id = group_expense.expense_id
        group_expense.destroy
        expense = Expense.delete(expense_id)
      end
      if @group.destroy
        redirect_to groups_path, notice: 'Groups was deleted successfully'
      else
        flash.now[:alert] = @group.errors.full_messages.first if @group.errors.any?
        render :index, status: 400
      end
    else
      flash[:alert] = 'Un Authorized'
      redirect_to groups_path
    end
  end
  # rubocop:enable Lint/UselessAssignment

  private

  def find_user
    @user = current_user
  end

  def find_group
    @group = Group.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = 'Group not found!'
    redirect_to not_found_index_path
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<div class="top_bar">
  <%= render partial: 'shared/menu', locals: { title: 'EDIT GROUP', menu_path: root_path } %>
</div>

<section class="edit_add_page group">
  <%= form_with model: @group, url: group_path(id: @group.id), local: true do |f| %>
    <%= f.text_field :name, autofocus: true %>
    <%= f.file_field :icon %>
    <div class="form_btn">
      <%= f.submit "Update Group", class: 'list_btn' %>
      <button class="list_btn"><%= link_to "Back", group_path(id: @group.id) %></button>
    </div>
  <% end %>
</section>

app/views/groups/index.html.erb
<div class="top_bar">
  <%= render partial: 'shared/menu', locals: { title: 'GROUPS', menu_path: root_path } %>
</div>

<section class="groups_page">
  <div>
    <% @groups.each do |group| %>
    <div class="group">
     <div>
      <a href=<%= group_expenses_path(group_id: group.id) %>>
        <% if group.icon.attached?%>
          <%= image_tag(group.icon) %>
        <%else%>
          <%= image_tag('group.png') %>
        <%end%>
        <!-- <%= image_tag(group.icon.attached? ? group.icon : 'group.png') %> -->
        <div>
          <h2><%= group.name %></h2>
          <% if Time.now - group.created_at <= 1.minute %>
            <p><%= time_ago_in_words(group.created_at, include_seconds: true) %> ago</p>
          <% elsif Time.now - group.created_at <= 24.hours %>
            <p><%= time_ago_in_words(group.created_at) %> ago</p>
          <% else %>
            <p><%= group.created_at.strftime('%b %d, %Y') %></p>
          <% end %>
        </div>
        </a>
      </div>
      <div class="list_gen">
        <h3>$ <%= group.expenses.sum(:amount) %></h3>
        <div class="btn_list">
          <button class="list_btn"><%= link_to 'Detail', group_path(id: group.id) %> </button>
          <button class="list_btn"><%= link_to 'Expense', group_expenses_path(group_id: group.id) %> </button>  
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <button class="add_btn"><%= link_to 'Add new group', new_group_path %> </button>
</section>

app/views/groups/new.html.erb
<div class="top_bar">
  <%= render partial: 'shared/menu', locals: { title: 'ADD GROUP', menu_path: root_path } %>
</div>

<section class="edit_add_page group">
  <%= form_with model: @group, url: groups_path, local: true do |f| %>
    <%= f.text_field :name, autofocus: true, placeholder: "Group name" %>
    <%= f.file_field :icon %>
    <div class="form_btn">
      <%= f.submit "Save", class: 'list_btn' %>
      <button class="list_btn"><%= link_to "Back", groups_path %></button>
    </div>
  <% end %>
</section>

app/views/groups/show.html.erb
<div class="top_bar">
  <%= render partial: 'shared/menu', locals: { title: 'GROUP DETAIL', menu_path: root_path } %>
</div>

<section class="group_detail_page">
  
  <div class="group">
    <div>
      <% if @group.icon.attached?%>
        <%= image_tag(@group.icon) %>
      <%else%>
        <%= image_tag('group.png') %>
      <%end%>
      <h2><%= @group.name %></h2>
    </div>
    <p class="desc">Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque iste quidem repudiandae. Dolor debitis quas impedit sit officiis dolorum beatae quaerat nesciunt doloribus expedita in distinctio laborum facilis ex sunt ipsum numquam, amet et odio iusto ab est. Vero, nemo.</p>
    
    <div class="list_btn_gen">
      <button class="edit_btn list_btn"><%= link_to "Edit", edit_group_path(@group) %></button>
      <button class="back_btn list_btn"><%= link_to "Back", groups_path %></button>
      <%= button_to "Delete", @group, method: :delete, class: 'del_btn list_btn' %>
    </div>
  </div>

</section>